made changes to make the ui work on the local branch but it still gives the same error as the one live on Berkeley TypeError: A.isConstant is not a function